### PR TITLE
Add hook chaining support

### PR DESCRIPTION
**Pull request by fallingcats**
Hook chaining significantly improves the speed at which certificates with many alt-names can be fetched by only waiting once for dns propagation after setting up all tokens.
I also made improvements in error reporting, showing only the errors and hiding successful responses.

### CODE REVIEW

**Comment by sineverba** [comment]
A very big thanks for your work!

**Comment by sineverba** [comment]
I will clean a bit the `CHANGELOG.md`, see differences (#Next version and double sharp on "old" versions). Just for your next PR :D

**Comment by fallingcats** [comment]
Thank you, I wan't sure how I should handle the Changelog

**Comment by sineverba** [comment]
Oh, simply... "reserve to me" the decision to make a new version, put your changes above a 

`#Next version`

tag. But, really, don't worry and another time... thank you ;)

**Pull request merged**
